"""empty message

Revision ID: 5434d5a936fc
Revises: None
Create Date: 2015-06-02 14:35:02.884604

"""

# revision identifiers, used by Alembic.
revision = '5434d5a936fc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
